// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCUSZT7KrtSApNJx_2ANzpyLFZiIxoC6Qk',
    appId: '1:672112100648:web:0c09fdc87fb5e7a6b53c1d',
    messagingSenderId: '672112100648',
    projectId: 'citizenship-academy-demo',
    authDomain: 'citizenship-academy-demo.firebaseapp.com',
    storageBucket: 'citizenship-academy-demo.firebasestorage.app',
    measurementId: 'G-N64G035K4V',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCKO8MzZSXDI74VPG-ILlhPe0PVWpjZg5I',
    appId: '1:672112100648:android:75d6114813067010b53c1d',
    messagingSenderId: '672112100648',
    projectId: 'citizenship-academy-demo',
    storageBucket: 'citizenship-academy-demo.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDZtirh9JcYoIrjfuXiBRFKyahGVRBkqkg',
    appId: '1:672112100648:ios:d8784b4f116b6917b53c1d',
    messagingSenderId: '672112100648',
    projectId: 'citizenship-academy-demo',
    storageBucket: 'citizenship-academy-demo.firebasestorage.app',
    iosBundleId: 'com.example.citizenshipAcademy',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDZtirh9JcYoIrjfuXiBRFKyahGVRBkqkg',
    appId: '1:672112100648:ios:d8784b4f116b6917b53c1d',
    messagingSenderId: '672112100648',
    projectId: 'citizenship-academy-demo',
    storageBucket: 'citizenship-academy-demo.firebasestorage.app',
    iosBundleId: 'com.example.citizenshipAcademy',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCUSZT7KrtSApNJx_2ANzpyLFZiIxoC6Qk',
    appId: '1:672112100648:web:166cd51f83b215bab53c1d',
    messagingSenderId: '672112100648',
    projectId: 'citizenship-academy-demo',
    authDomain: 'citizenship-academy-demo.firebaseapp.com',
    storageBucket: 'citizenship-academy-demo.firebasestorage.app',
    measurementId: 'G-TJQV1VGJ76',
  );
}
